### ISSUE TITLE
If Credit Card Payment is Declined the user is returned to the Cart

### ISSUE THREAD

**Issue by mtrutledge** [HotcakesCommerce/core#120]
**Reproduction Steps:**
1. Setup a Demo Hotcakes Store
2. Configure the Payment Methods to be:
  - Credit Card - Authorize.NET in Developer Mode
  - Charge full amount on ordering
  - Require CVV code
3. Go to the store and add an item to the cart
4. Click Secure Checkout
5. Fill out the shipping address. In the ZIP CODE field put in **46282** (This tells Authorize.NET to treat this as a declined credit card purchase)
6. Use credit card number 4111111111111111 with any expiration date in the future and any 3 digits for the CVV code.

**Expected Behavior:** The order should be created in hotcakes, however it should not be marked as paid. The user should be directed to the Checkout/action/paymenterror page to be prompted to update their billing address and payment details.

**Actual Behavior:** The order is created in hotcakes and is not marked as paid as expected. However, the user is directed to the Cart page where it does not show any items.

**What is causing the issue:**
Once the order is created in the first step of the workflow the cookie that stores the cart id is set to 0. Any call to CurrentCart will then return null.

CheckoutController.cs
```

private void ProcessOrder(CheckoutViewModel model)
 {
.....
// Starting at Line: 1136 and 1137 in CheckoutController.cs
// Clear Cart ID because we're now an order
SessionManager.SetCurrentCartId(HccApp.CurrentStore, string.Empty);
                    // Process Payment
                    if (Workflow.RunByName(c, WorkflowNames.ProcessNewOrderPayments))
                    {
....
                    }
                    else
                    {
                        // Redirect to Payment Error
                        SessionManager.SetCurrentPaymentPendingCartId(HccApp.CurrentStore, model.CurrentOrder.bvin);
                        Response.Redirect(Url.RouteHccUrl(HccRoute.Checkout, new {action = "paymenterror"}));
                    }
}

```

CheckoutController.PaymentError.cs
```
                [HccHttpGet]
		[NonCacheableResponseFilter]
		public ActionResult PaymentError()
		{
			if (CurrentCart == null || CurrentCart.Items == null || CurrentCart.Items.Count == 0)
			{
				Response.Redirect(Url.RouteHccUrl(HccRoute.Cart));
			}

			CheckoutViewModel model = PaymentErrorSetup();
			if (ValidateSession(model))
			{
				return Redirect(Url.RouteHccUrl(HccRoute.Checkout));
			}


			RenderErrorSummary(model);
			return View(model);
		}

```

If you remove the following from the above function:
```
		if (CurrentCart == null || CurrentCart.Items == null || CurrentCart.Items.Count == 0)
			{
				Response.Redirect(Url.RouteHccUrl(HccRoute.Cart));
			}

```
Then everything will work properly.

**Comment by mtrutledge** [comment]
I can do this change and create a pull request.

**Comment by mtrutledge** [comment]
Ok I have created a pull request https://github.com/HotcakesCommerce/core/pull/121

**Comment by hismightiness** [comment]
Outstanding stuff!  Thanks, Matt!

**Comment by hismightiness** [comment]
Tested and this appears to be the fix.  Thanks, Matt! :)

**Comment by mtrutledge** [comment]
Awesome! Glad to help.
