### ISSUE TITLE
Dnn9 issues

### ISSUE THREAD

**Issue by kurtwilbies** [HotcakesCommerce/core#17]
Hotcakes does noet work with dnn9 personabar. How to fix this issue?

**Comment by hismightiness** [comment]
Hello @kurtwilbies 

Thanks for asking.  Unfortunately, DNN 9 features aren't compatible with Hotcakes 3.0.  There isn't really anything to fix.  However, if someone would like to create a pull request to port the persona bar features into Hotcakes, we'd definitely be interested in talking about that.

**Comment by kurtwilbies** [comment]
Hello @hismightiness 

It is not necessary to let dnn9 feature be compatible with hotcakes. The only thing is that I only use the personabar and not the old dnn-8 menu. Its not one od the other. They can co-existin one install. Is this true?

**Comment by moslem7026** [comment]
DNN 9 has been Improved in Performance and UI, 
Let Talk about Problems of HCC 3 and DNN9 issues and solve them.
