### ISSUE TITLE
Unsure what to do

### ISSUE THREAD

**Issue by kurtwilbies** [HotcakesCommerce/core#18]
I managed to let hotcakes work nicely with dnn9.10. However, I don't know whether I can use it in a production env. Are there know security risks in doing so? Do I have to add/change something? Please let me know.

**Comment by hismightiness** [comment]
Hello @kurtwilbies 

Unfortunately, Hotcakes 3.0 isn't compatible with DNN 9.  Sorry.

**Comment by kurtwilbies** [comment]
Thanks hismighttiness. Do you think its wise to use in a production env. If we managed to let hotcakes work with dnn9.
Is there a security risk in letting both hotcakes3 and dnn9 work together?
