### ISSUE TITLE
Items cannot be added to cart if .NET incorrectly detects browser cookie capability

### ISSUE THREAD

**Issue by MarkXA** [HotcakesCommerce/core#20]
Hotcakes uses .NET browser capability detection to check whether clients support cookies. If not, it neither reads nor sets cookies, which prevents cart contents from being remembered. This means that if a browser's capabilities are wrongly detected then the Hotcakes cart is always empty.

These checks should be removed so that cookies are always used. In the unlikely event that the browser doesn't support cookies, the server check is superfluous anyway.

**Comment by hismightiness** [comment]
Hello Mark:

Thanks for posting this.  Are you talking about this?

https://github.com/HotcakesCommerce/core/blob/master/Libraries/Hotcakes.Web/Cookies.cs#L124
