### ISSUE TITLE
List of issues

### ISSUE THREAD

**Issue by kurtwilbies** [HotcakesCommerce/core#21]
What makes hcc3 CORE really not working on OR incompatible with dnn9.xx? Do you have a list of possible issues? If I have more indepth info then I could try to make it compatible.

**Comment by kurtwilbies** [comment]
I tested hcc3 als a module in dnn9 and it is working nice in dev mode. No issues so far. Do you or colleagues know of possible compatibilty issues or bugs when using dnn9 and above?

**Comment by hismightiness** [comment]
There are currently no plans to develop compatibility with DNN 9.

**Comment by kurtwilbies** [comment]
What are the plans for the future?
