### ISSUE TITLE
Add New Capability to set Decimal point in Price

### ISSUE THREAD

**Issue by moslem7026** [HotcakesCommerce/core#22]
In Hotcakes I cant see any option to customize Price  and adjust price unit
8.99 or 8.9 or 8 and and Price Unit Rial and $ and other unit .
Price Unit just Set By Culture Info that is not really Customizable .

**Comment by hismightiness** [comment]
Please see the following documentation:

https://support.upendoventures.com/hc/en-us/articles/208945486-Settings-Geo-Location
