### ISSUE TITLE
Hotcakes Cloud environment MVC upgraded

### ISSUE THREAD

**Issue by hismightiness** [HotcakesCommerce/core#24]
The Hotcakes Cloud environment now has a newer version of MVC applied by default. This means we can revert the Cloud-specific configuration setting.

**Comment by kurtwilbies** [comment]
What does this mean. Is hcc compatible with dnn9? I tested hcc3 als a module in dnn9 and it is working nice in dev mode. No issues so far. Do you or colleagues know of possible compatibilty issues or bugs when using dnn9 and above?

**Comment by hismightiness** [comment]
@kurtwilbies The Hotcakes Cloud and DNN are not the same thing. Sorry.
