### ISSUE TITLE
In DNN9.1 two .dll

### ISSUE THREAD

**Issue by kurtwilbies** [HotcakesCommerce/core#28]
When installing hcc3 on dnn9.1 It works well, but I get TWO .dll, one dotnetnuke and the other is hcc-cms-related. I assume this is why hcc3 works on dnn9.1. I put hudge amount of efforts to understand all the pieces and why hcc3 works on dnn9.1. But really I need more information about the major (infrastructure related) decisions: maybe a graph of all the related components!

**Comment by hismightiness** [comment]
There are currently no plans to develop compatibility with DNN 9.

**Comment by kurtwilbies** [comment]
What are the plans for the future?
