### ISSUE TITLE
No documentation

### ISSUE THREAD

**Issue by kurtwilbies** [HotcakesCommerce/core#5]
There is virtually no documentation on how to install and use this project. Please provide us with the necessary info to install and use this project. And preferably an install release so that we can use existing tools to istall this project. And maybe a brief intro into the various core hotcakes only code.

**Comment by hismightiness** [comment]
You'll find documentation and installation packages on the official project website.

https://hotcakes.org

**Comment by mrswoop** [comment]
More specifically, please reference the installation documentation here:
https://hotcakescommerce.zendesk.com/hc/en-us/articles/115002941503-Installing-Hotcakes-Commerce
