### ISSUE TITLE
No istall package

### ISSUE THREAD

**Issue by kurtwilbies** [HotcakesCommerce/core#6]
Please publish an install package, and/or docs on how to install the pieces.

**Comment by hismightiness** [comment]
You'll find installation instructions, documentation, and installation packages on the official project website.

https://hotcakes.org

**Comment by mrswoop** [comment]
Installation instructions can be found here:
https://hotcakescommerce.zendesk.com/hc/en-us/articles/115002941503-Installing-Hotcakes-Commerce
