### ISSUE TITLE
Module Solution Installer possibly has stray file in zip

### ISSUE THREAD

**Issue by moorecreative** [HotcakesCommerce/core#62]
review the installer package for 3.0.1
      Hotcakes_03.00.01_Core_Install.zip

I don't know whether this was an unintentional stray file, or whether it is intentionally in the zip in this location, but I noticed that there is a dll in the root of the installer zip file
"System.Web.Mvc.dll"
vs in the bin folder

* Note: I really didn't know where to post this note/issue... this applies to the module solution version of Hotcakes, so perhaps it should be in the "modules" location in github. However, the zip file installer is called "core" so I've placed it here... though "core" in github seems to refer to the hotcakes-specific core files vs the DNN/cms or full hotcakes cms solution. SO, move this where appropriate

**Comment by hismightiness** [comment]
Thanks for the issue.  This isn't a new thing.  We've had the DLL in the root of the module package since the beginning.  It's there for specific installation scenarios to ensure MVC compatibility/integration in DNN.
